# Uncomment the next line to define a global platform for your project
platform :ios, '14.4'
inhibit_all_warnings!

target 'BerlinClock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BerlinClock
  pod 'SwiftLint'

  target 'BerlinClockTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BerlinClockUITests' do
    # Pods for testing
  end

end